language: python
python:
  - 3.3
  - 3.4
  - 3.5
sudo: false

install:
  - pip install nose-cov codecov python-coveralls

script:
  - nosetests --with-cov --cov anagram

# Calculate coverage
after_success:
  - coveralls
  - codecov

notifications:
  email:
    - brendan@bitsmithy.net
